# Nome unico do servico no Eureka
spring.application.name=auth-service

# Porta do servico
server.port=8081

# Endereco do Servidor Eureka
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

# ===============================================
# CONFIGURACAO DO BANCO DE DADOS (POSTGRESQL)
# ===============================================
# Lembre-se de verificar a porta do seu postgres-auth no docker-compose.yml
spring.datasource.url=jdbc:postgresql://localhost:5434/pixpro_auth_db
spring.datasource.username=postgres
spring.datasource.password=admin

# =.=============================================
# CONFIGURACAO DO HIBERNATE (JPA)
# ===============================================
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# ===============================================
# CONFIGURACAO DO JWT
# ===============================================
jwt.secret.key=a2a6293f7f22f87a87c061b52a201c8286add5f7a083f2a3f7f87c061b52a201

# ===============================================
# CONFIGURACAO DO ADMIN INICIAL
# ===============================================
admin.email=admin@pixpro.com
admin.password=admin1234