spring.application.name=notification-service
# Uma nova porta para este servico
server.port=8443

# Configuracao do Eureka
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

# Configuracao do Consumidor Kafka
spring.kafka.consumer.group-id=notification-service-group

# ===============================================
# CONFIGURACAO DO JWT
# ===============================================
jwt.secret.key=a2a6293f7f22f87a87c061b52a201c8286add5f7a083f2a3f7f87c061b52a201


# ===============================================
# CONFIGURAÇÃO DE SSL (HTTPS/WSS)
# ===============================================

# Habilita o SSL
server.ssl.enabled=true

# Tipo do arquivo de certificado que geramos
server.ssl.key-store-type=PKCS12

# Caminho para o certificado (o "classpath:" aponta para a pasta /resources)
server.ssl.key-store=classpath:keystore.p12

# A senha que definimos no keytool
server.ssl.key-store-password=pixpro123

# O "apelido" que demos à nossa chave
server.ssl.key-alias=pixpro-ssl